import React from 'react';
import './style.css';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import axios from 'axios';

function ProjectsList() {
  const data = {
    pageProps: {
      projetos: [
        {
          slug: 'projeto-pronto-casa-terrea-2-suites-nevada',
          Nome: 'Nevada',
          TipoConstrucao: 'Térrea',
          Codigo: '165',
          midia: {
            thumbnail: {
              url: '/uploads/CAPA_SITE_027b6b55b0.jpg',
              width: 960,
              height: 540,
              alternativeText: 'fachada de casa térrea moderna',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 18,
          ComprimentoTerreno: 30,
          AreaConstruida: 170.8,
          Quarto: 3,
          Banheiro: 4,
          Garagem: 2,
          MiniDescricao: 'Projeto Pronto de Casa Térrea Com 2 Suítes',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-pronta-de-casa-com-70-metros-quioto',
          Nome: 'Quioto',
          TipoConstrucao: 'térrea',
          Codigo: '164',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_quioto_a1bd3c983e.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 5,
          ComprimentoTerreno: 25,
          AreaConstruida: 59.97,
          Quarto: 2,
          Banheiro: 1,
          Garagem: 1,
          MiniDescricao: 'Planta Pronta de Casa com 70 metros',
          AreaGourmet: false,
          Piscina: false,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-sobrado-neoclassico-pe-direito-duplo-roma',
          Nome: 'Roma',
          TipoConstrucao: 'sobrado',
          Codigo: '163',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_roma_08c06156e9.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 20,
          ComprimentoTerreno: 40,
          AreaConstruida: 416.97,
          Quarto: 4,
          Banheiro: 5,
          Garagem: 2,
          MiniDescricao: 'Projeto Pronto de Sobrado com Pé Direito Duplo',
          AreaGourmet: true,
          Piscina: false,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-casa-com-4-suites-fachada-moderna-bali',
          Nome: 'Bali',
          TipoConstrucao: 'sobrado',
          Codigo: '162',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_bali_16f95fd663.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 17,
          ComprimentoTerreno: 27,
          AreaConstruida: 316.98,
          Quarto: 4,
          Banheiro: 6,
          Garagem: 2,
          MiniDescricao: 'Planta de Casa com 4 Suítes e Fachada Moderna',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-sobrado-3-suites-fachada-imponente-viena',
          Nome: 'Viena',
          TipoConstrucao: 'sobrado',
          Codigo: '159',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_viena_b80bc127f9.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 15,
          ComprimentoTerreno: 40,
          AreaConstruida: 303.42,
          Quarto: 4,
          Banheiro: 4,
          Garagem: 2,
          MiniDescricao: 'Projeto de Sobrado com 4 Suítes e Fachada Imponente',
          AreaGourmet: true,
          Piscina: false,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-casa-de-campo-com-3-quartos-cordova',
          Nome: 'Córdova',
          TipoConstrucao: 'sobrado',
          Codigo: '161',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_cordova_cee1176276.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 30,
          ComprimentoTerreno: 49,
          AreaConstruida: 273.54,
          Quarto: 3,
          Banheiro: 2,
          Garagem: 2,
          MiniDescricao: 'Planta de Casa de Campo com 3 Quartos e Varanda',
          AreaGourmet: true,
          Piscina: false,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-de-casa-pequena-e-moderna-turquia',
          Nome: 'Turquia',
          TipoConstrucao: 'Sobrado',
          Codigo: '158',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_turquia_7b69923008.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 6,
          ComprimentoTerreno: 24.5,
          AreaConstruida: 150.57,
          Quarto: 3,
          Banheiro: 3,
          Garagem: 1,
          MiniDescricao: 'Projeto de Casa Pequena e Moderna',
          AreaGourmet: true,
          Piscina: false,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-pronta-de-sobrado-com-piscina-e-area-gourmet-georgia',
          Nome: 'Geórgia',
          TipoConstrucao: 'Sobrado',
          Codigo: '157',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_georgia_106a209e9a.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 12,
          ComprimentoTerreno: 37,
          AreaConstruida: 285.72,
          Quarto: 3,
          Banheiro: 4,
          Garagem: 2,
          MiniDescricao:
            'Planta Pronta de Casa Térrea com Piscina e Área Gourmet',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-casa-com-3-suítes-e-piscina-com-deck-genebra',
          Nome: 'Genebra',
          TipoConstrucao: 'sobrado',
          Codigo: '156',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_genebra_4e29f89755.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 17,
          ComprimentoTerreno: 30,
          AreaConstruida: 241.57,
          Quarto: 3,
          Banheiro: 5,
          Garagem: 2,
          MiniDescricao: 'Planta de Casa com 3 Suítes  e Piscina Com Deck',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-casa-de-campo-3-quartos-havana',
          Nome: 'Havana',
          TipoConstrucao: 'sobrado',
          Codigo: '160',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_havana_9d4774ffad.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 13.7,
          ComprimentoTerreno: 27,
          AreaConstruida: 169.25,
          Quarto: 3,
          Banheiro: 3,
          Garagem: 1,
          MiniDescricao: 'Projeto de Casa de Campo Com 3 Quartos',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-sobrado-com-pe-direto-duplo-marrocos',
          Nome: 'Marrocos',
          TipoConstrucao: 'sobrado',
          Codigo: '154',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_marrocos_7bed3f94f2.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 10,
          ComprimentoTerreno: 20,
          AreaConstruida: 166.89,
          Quarto: 3,
          Banheiro: 3,
          Garagem: 2,
          MiniDescricao: 'Projeto de sobrado pequeno com pé direito duplo',
          AreaGourmet: true,
          Piscina: false,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-pronto-com-4-quartos-pe-direito-duplo-taiwan',
          Nome: 'Taiwan',
          TipoConstrucao: 'sobrado',
          Codigo: '153',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_taiwan_6c48b08ca0.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 10,
          ComprimentoTerreno: 20,
          AreaConstruida: 302.94,
          Quarto: 4,
          Banheiro: 5,
          Garagem: 1,
          MiniDescricao: 'Projeto Pronto Com 4 Quartos e Pé Direito Duplo',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-casa-terrea-com-3-quartos-munique',
          Nome: 'Munique',
          TipoConstrucao: 'Térrea',
          Codigo: '152',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_munique_1d4e1b8c1f.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 13,
          ComprimentoTerreno: 40,
          AreaConstruida: 215.89,
          Quarto: 3,
          Banheiro: 3,
          Garagem: 2,
          MiniDescricao:
            'Planta de Casa Térrea Com 3 Quartos e Conceito Aberto',
          AreaGourmet: true,
          Piscina: false,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-pronta-terrea-conceito-aberto-montevideu',
          Nome: 'Montevidéu',
          TipoConstrucao: 'Térrea',
          Codigo: '150',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_montevideu_9741924b6b.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 17,
          ComprimentoTerreno: 30,
          AreaConstruida: 246.28,
          Quarto: 3,
          Banheiro: 5,
          Garagem: 3,
          MiniDescricao: 'Planta Pronta de Casa Térrea Com Conceito Aberto',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-sobrado-pe-direito-duplo-belgica',
          Nome: 'Bélgica',
          TipoConstrucao: 'Sobrado',
          Codigo: '149',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_belgica_ba24edf015.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 10,
          ComprimentoTerreno: 20,
          AreaConstruida: 204.28,
          Quarto: 3,
          Banheiro: 3,
          Garagem: 2,
          MiniDescricao: 'Projeto de Sobrado Com Pé Direito Duplo',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-casa-conceito-aberto-toronto',
          Nome: 'Toronto',
          TipoConstrucao: 'Terrea',
          Codigo: '155',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_toronto_a694cd61f1.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 14,
          ComprimentoTerreno: 35,
          AreaConstruida: 222.46,
          Quarto: 3,
          Banheiro: 3,
          Garagem: 2,
          MiniDescricao:
            'Planta de Casa Térrea Com 3 Quartos e Conceito Aberto',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-pronto-casa-terrea-3-quartos-uruguai',
          Nome: 'Uruguai',
          TipoConstrucao: 'Térrea',
          Codigo: '148',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_uruguai_27ff9efc6f.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 10,
          ComprimentoTerreno: 25,
          AreaConstruida: 96.12,
          Quarto: 3,
          Banheiro: 2,
          Garagem: 2,
          MiniDescricao: 'Projeto Pronto de Casa Térrea Com 3 Quartos',
          AreaGourmet: false,
          Piscina: false,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-pronto-3-suites-e-area-gourmet',
          Nome: 'Dublin',
          TipoConstrucao: 'Sobrado',
          Codigo: '147',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_dublin_638f65167f.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 14,
          ComprimentoTerreno: 30,
          AreaConstruida: 231.02,
          Quarto: 3,
          Banheiro: 5,
          Garagem: 2,
          MiniDescricao: 'Projeto Pronto de Casa com 3 Suítes e Área Gourmet',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-casa-com-3-quartos-e-piscina',
          Nome: 'Lisboa',
          TipoConstrucao: 'sobrado',
          Codigo: '146',
          midia: {
            thumbnail: {
              url: '/uploads/CAPA_SITE_6f1f01107b.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 13,
          ComprimentoTerreno: 30,
          AreaConstruida: 252.29,
          Quarto: 3,
          Banheiro: 4,
          Garagem: 2,
          MiniDescricao: 'Planta de Casa Com 252 m², 3 Quartos e Piscina',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-casa-em-aclive-america',
          Nome: 'América',
          TipoConstrucao: 'Sobrado',
          Codigo: '145',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_america_663d39ad11.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 14,
          ComprimentoTerreno: 25,
          AreaConstruida: 211.25,
          Quarto: 3,
          Banheiro: 3,
          Garagem: 2,
          MiniDescricao: 'Planta de Casa Moderna em Aclive com Área Gourmet',
          AreaGourmet: true,
          Piscina: false,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'sobrado-com-3-suite-beverly-hills',
          Nome: 'Beverly Hills',
          TipoConstrucao: 'Sobrado',
          Codigo: '144',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_beverly_hills_a0d8b4901a.jpg',
              width: 960,
              height: 540,
              alternativeText: '',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 20,
          ComprimentoTerreno: 25.1,
          AreaConstruida: 306.21,
          Quarto: 3,
          Banheiro: 5,
          Garagem: 2,
          MiniDescricao: ' Projeto de Sobrado com 3 Suítes e Piscina',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-residencial-com-3-suites-e-quadra-de-esportes-detroit',
          Nome: 'Detroit',
          TipoConstrucao: 'Sobrado',
          Codigo: '143',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_detroit_e9d8aa6d08.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Detroit da Archshop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 30,
          ComprimentoTerreno: 30,
          AreaConstruida: 317.81,
          Quarto: 3,
          Banheiro: 5,
          Garagem: 2,
          MiniDescricao:
            'Projeto Residencial Com 3 Suítes e Quadra de Esportes',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-terreo-com-3-quartos-e-area-gourmet-napoles',
          Nome: 'Nápoles',
          TipoConstrucao: 'Térrea',
          Codigo: '142',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_napoles_8f092c9eca.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Nápoles da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 12,
          ComprimentoTerreno: 30,
          AreaConstruida: 173.97,
          Quarto: 3,
          Banheiro: 3,
          Garagem: 2,
          MiniDescricao: 'Projeto de Casa Térrea Com 3 Quartos e Área Gourmet',
          AreaGourmet: true,
          Piscina: false,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-casa-com-4-suites-e-spa-singapura',
          Nome: 'Singapura',
          TipoConstrucao: 'Térrea',
          Codigo: '141',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_singapura_5f7538aeb7.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Singapura da Archshop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 25,
          ComprimentoTerreno: 50,
          AreaConstruida: 352.25,
          Quarto: 4,
          Banheiro: 6,
          Garagem: 2,
          MiniDescricao: 'Planta de Casa Com 4 Suítes, Spa e Fogo de Chão',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-de-alto-padrao-com-5-quartos-e-fachada-moderna-caribe',
          Nome: 'Caribe',
          TipoConstrucao: 'Sobrado',
          Codigo: '140',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_caribe_1b09d3af82.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Caribe da Archshop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 30,
          ComprimentoTerreno: 40,
          AreaConstruida: 653.26,
          Quarto: 5,
          Banheiro: 7,
          Garagem: 3,
          MiniDescricao:
            'Projeto de Alto Padrão Com 5 quartos e Fachada Moderna',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-de-sobrado-com-2-suites-e-jardim-de-inverno-amsterda',
          Nome: 'Amsterdã',
          TipoConstrucao: 'Sobrado',
          Codigo: '139',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_amsterda_745a5914a0.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Amsterdã da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 6,
          ComprimentoTerreno: 25,
          AreaConstruida: 151.5,
          Quarto: 2,
          Banheiro: 3,
          Garagem: 1,
          MiniDescricao:
            'Projeto de Sobrado Com 2 Suítes, Jardim de Inverno e Área Gourmet',
          AreaGourmet: true,
          Piscina: false,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-de-casa-terrea-com-fogo-de-chao-barcelona',
          Nome: 'Barcelona',
          TipoConstrucao: 'Térrea',
          Codigo: '138',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_barcelona_de50b3aad7.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Barcelona da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 25,
          ComprimentoTerreno: 35,
          AreaConstruida: 294.1,
          Quarto: 3,
          Banheiro: 5,
          Garagem: 3,
          MiniDescricao:
            'Projeto de Casa Térrea Com 3 Suítes, Fogo de Chão e Área de Descanso',
          AreaGourmet: true,
          Piscina: false,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-pronta-com-4-suites-area-gourmet-e-piscina-berlin',
          Nome: 'Berlin',
          TipoConstrucao: 'Sobrado',
          Codigo: '137',
          midia: {
            thumbnail: {
              url: '/uploads/CAPA_SITE_berlim_255068a06d.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Berlim da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 25,
          ComprimentoTerreno: 30,
          AreaConstruida: 355.25,
          Quarto: 4,
          Banheiro: 5,
          Garagem: 2,
          MiniDescricao:
            'Planta Pronta Com 4 Suítes, Área Gourmet e Piscina com Deck',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-casa-terrea-com-4-suites-area-gourmet-miami',
          Nome: 'Miami',
          TipoConstrucao: 'Térrea',
          Codigo: '136',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_miami_1474ffdca3.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Miami da Archshop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 25,
          ComprimentoTerreno: 40,
          AreaConstruida: 346.07,
          Quarto: 4,
          Banheiro: 5,
          Garagem: 3,
          MiniDescricao:
            'Planta de Casa Térrea Com 4 Suítes, Área Gourmet e Piscina',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-residencial-com-pe-direito-duplo-e-5-suites-buenos-aires',
          Nome: 'Buenos Aires',
          TipoConstrucao: 'Sobrado',
          Codigo: '135',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_buenos_aires_fcf2a03960.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Buenos Aires da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 25,
          ComprimentoTerreno: 50,
          AreaConstruida: 444.46,
          Quarto: 5,
          Banheiro: 7,
          Garagem: 2,
          MiniDescricao:
            'Projeto de Casa Com Pé Direito Duplo, 5 Suítes e Deck Com Vista',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-pronta-com-3-dormitorios-com-pe-direito-duplo-portugal',
          Nome: 'Portugal',
          TipoConstrucao: 'Sobrado',
          Codigo: '134',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_portugal_6201695467.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Portugal da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 17,
          ComprimentoTerreno: 28,
          AreaConstruida: 317.25,
          Quarto: 3,
          Banheiro: 3,
          Garagem: 2,
          MiniDescricao:
            'Planta Pronta Com 3 Dormitórios, Pé Direito Duplo e Conceito Aberto',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-de-casa-terrea-com-3-suites-e-area-gourmet-dallas',
          Nome: 'Dallas',
          TipoConstrucao: 'Térrea',
          Codigo: '133',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_dallas_4843ff0fc6.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Dallas da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 10,
          ComprimentoTerreno: 25,
          AreaConstruida: 168,
          Quarto: 3,
          Banheiro: 3,
          Garagem: 2,
          MiniDescricao: 'Projeto de Casa Térrea Com 3 Suítes e Área Gourmet',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-pronto-com-3-suites-e-area-gourmet-colombia',
          Nome: 'Colômbia',
          TipoConstrucao: 'Sobrado',
          Codigo: '132',
          midia: {
            thumbnail: {
              url: '/uploads/CAPA_SITE_colombia_57f1896b42.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Colômbia da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 23,
          ComprimentoTerreno: 30,
          AreaConstruida: 304.71,
          Quarto: 4,
          Banheiro: 4,
          Garagem: 2,
          MiniDescricao:
            'Projeto Pronto Para Declive Com 3 Suítes e Área Gourmet',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-casa-com-3-suites-e-fachada-moderna-florenca',
          Nome: 'Florença',
          TipoConstrucao: 'Sobrado',
          Codigo: '131',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_florenca_15f5041767.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Florença da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 10,
          ComprimentoTerreno: 25,
          AreaConstruida: 236.62,
          Quarto: 3,
          Banheiro: 4,
          Garagem: 1,
          MiniDescricao:
            'Planta de Casa Com Fachada Moderna, 3 Suítes e Área de Descanso',
          AreaGourmet: true,
          Piscina: false,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-pronto-de-sobrado-com-4-quartos-e-piscina-milao',
          Nome: 'Milão',
          TipoConstrucao: 'Sobrado',
          Codigo: '130',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_milao_1faad3ec3e.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Milão da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 12,
          ComprimentoTerreno: 35,
          AreaConstruida: 217.63,
          Quarto: 4,
          Banheiro: 5,
          Garagem: 2,
          MiniDescricao: 'Projeto Pronto de Sobrado Com 4 Quartos e Piscina',
          AreaGourmet: false,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-pronta-de-casa-com-conceito-aberto-e-piscina-finlandia',
          Nome: 'Finlândia',
          TipoConstrucao: 'Térrea',
          Codigo: '129',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_finlandia_874300ab37.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Finlândia da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 10,
          ComprimentoTerreno: 50,
          AreaConstruida: 200.91,
          Quarto: 2,
          Banheiro: 3,
          Garagem: 2,
          MiniDescricao:
            'Planta Pronta Com Conceito Aberto, 2 Quartos e Área Gourmet',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-terreo-para-terreno-12-x-25-londres',
          Nome: 'Londres',
          TipoConstrucao: 'Térrea',
          Codigo: '128',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_londres_2a803d6c58.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Londres da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 12,
          ComprimentoTerreno: 25,
          AreaConstruida: 154.95,
          Quarto: 2,
          Banheiro: 2,
          Garagem: 2,
          MiniDescricao:
            'Projeto Térreo Para Terreno 12x25 Com 2 Suítes e Área Gourmet',
          AreaGourmet: true,
          Piscina: false,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-sobrado-com-3-suites-e-pe-direito-duplo-budapeste',
          Nome: 'Budapeste',
          TipoConstrucao: 'Sobrado',
          Codigo: '127',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_budapeste_3c1524e6b0.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Budapeste da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 14,
          ComprimentoTerreno: 30,
          AreaConstruida: 293.17,
          Quarto: 3,
          Banheiro: 5,
          Garagem: 2,
          MiniDescricao:
            'Projeto de Sobrado Com 3 Suítes e Área de Lazer Completa',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-casa-meio-lote-2-quartos-moscou',
          Nome: 'Moscou',
          TipoConstrucao: 'Térrea',
          Codigo: '126',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_moscou_6ed1efd407.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Moscou da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 5,
          ComprimentoTerreno: 25,
          AreaConstruida: 69.7,
          Quarto: 2,
          Banheiro: 1,
          Garagem: 1,
          MiniDescricao:
            'Projeto de Casa Meio Lote Com 2 Quartos e Área Gourmet',
          AreaGourmet: true,
          Piscina: false,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-de-casa-com-fogo-de-chao-e-conceito-aberto-atlanta',
          Nome: 'Atlanta',
          TipoConstrucao: 'Térrea',
          Codigo: '125',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_atlanta_cda9f90447.png',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Atlanta da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 12,
          ComprimentoTerreno: 30,
          AreaConstruida: 310.62,
          Quarto: 4,
          Banheiro: 6,
          Garagem: 2,
          MiniDescricao:
            'Projeto de Casa Com Fogo de Chão e Ambientes Integrados',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-pronta-de-sobrado-com-conceito-aberto-zurich',
          Nome: 'Zurich',
          TipoConstrucao: 'Sobrado',
          Codigo: '124',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_zurich_0fc353fa0d.png',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Zurich da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 13,
          ComprimentoTerreno: 30,
          AreaConstruida: 191.8,
          Quarto: 4,
          Banheiro: 3,
          Garagem: 2,
          MiniDescricao:
            'Planta Pronta de Sobrado Com 4 Quartos e Conceito Aberto',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-terreo-com-3-suites-e-ambientes-integrdos-filipinas',
          Nome: 'Filipinas',
          TipoConstrucao: 'Térrea',
          Codigo: '123',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_filipinas_115afb45bc.png',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Filipinas da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 22,
          ComprimentoTerreno: 30,
          AreaConstruida: 273.26,
          Quarto: 3,
          Banheiro: 4,
          Garagem: 2,
          MiniDescricao: 'Projeto Térreo Com 3 Suítes e Ambientes Integrados',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-de-casa-terrea-com-4-dormitorios-malasia',
          Nome: 'Malásia',
          TipoConstrucao: 'Térrea',
          Codigo: '122',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_malasia_8d24db88f8.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Malásia da Archshop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 26.53,
          ComprimentoTerreno: 31.5,
          AreaConstruida: 372.7,
          Quarto: 4,
          Banheiro: 6,
          Garagem: 2,
          MiniDescricao:
            'Projeto de Casa Térrea com 4 Dormitórios e Área de Lazer Completa',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-residencial-com-cinema-e-varanda-gourmet-madagascar',
          Nome: 'Madagascar',
          TipoConstrucao: 'Sobrado',
          Codigo: '121',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_madagascar_2ab3bf06e9.png',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Madagascar da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 16,
          ComprimentoTerreno: 22,
          AreaConstruida: 328.51,
          Quarto: 3,
          Banheiro: 6,
          Garagem: 2,
          MiniDescricao:
            'Projeto Residencial Com Cinema, 4 Suítes e Varanda Gourmet',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-para-casa-de-alto-padrao-com-4-suites-toquio',
          Nome: 'Tóquio',
          TipoConstrucao: 'Sobrado',
          Codigo: '120',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_toquio_d7a15fafab.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Tóquio da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 13.9,
          ComprimentoTerreno: 29.9,
          AreaConstruida: 289.11,
          Quarto: 4,
          Banheiro: 5,
          Garagem: 2,
          MiniDescricao:
            'Projeto de Casa Alto Padrão Com 4 Suítes e Fogo de Chão',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-casa-com-69-m2-e-2-quartos-guatemala',
          Nome: 'Guatemala',
          TipoConstrucao: 'Térrea',
          Codigo: '119',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_guatemala_9985618c9d.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Guatemala da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 6.05,
          ComprimentoTerreno: 25.1,
          AreaConstruida: 68.23,
          Quarto: 2,
          Banheiro: 2,
          Garagem: 0,
          MiniDescricao: 'Planta de Casa Com 69 m² e ambientes integrados',
          AreaGourmet: false,
          Piscina: false,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-de-casa-terrea-conceito-aberto-e-2-quartos-turim',
          Nome: 'Turim',
          TipoConstrucao: 'Térrea',
          Codigo: '118',
          midia: {
            thumbnail: {
              url: '/uploads/CAPA_SITE_turim_9b4d8f795c.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Turim da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 15,
          ComprimentoTerreno: 25,
          AreaConstruida: 105.06,
          Quarto: 1,
          Banheiro: 2,
          Garagem: 2,
          MiniDescricao:
            'Projeto de Casa Térrea Com Conceito Aberto e 2 Quartos',
          AreaGourmet: true,
          Piscina: false,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-pronta-de-casa-de-campo-california',
          Nome: 'Califórnia',
          TipoConstrucao: 'Térrea',
          Codigo: '117',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_california_d697dd7733.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Califórnia da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 50,
          ComprimentoTerreno: 60,
          AreaConstruida: 285.79,
          Quarto: 4,
          Banheiro: 6,
          Garagem: 2,
          MiniDescricao: 'Planta Pronta de Casa de Campo Térrea Com 4 Suítes',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-de-sobrado-com-pe-direito-duplo-memphis',
          Nome: 'Memphis',
          TipoConstrucao: 'Sobrado',
          Codigo: '116',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_memphis_244b444c62.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Memphis da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 12,
          ComprimentoTerreno: 35,
          AreaConstruida: 262.48,
          Quarto: 4,
          Banheiro: 6,
          Garagem: 2,
          MiniDescricao:
            'Projeto de Sobrado Com Pé Direito Duplo e Fachada Imponente',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-casa-com-conceito-aberto-noruega',
          Nome: 'Noruega',
          TipoConstrucao: 'Térrea',
          Codigo: '115',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_noruega_e7a97e67d5.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Noruega da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 10,
          ComprimentoTerreno: 25,
          AreaConstruida: 153.46,
          Quarto: 3,
          Banheiro: 3,
          Garagem: 1,
          MiniDescricao: 'Planta de Casa Com 3 Quartos e Conceito Aberto',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-de-casa-pequena-com-conceito-aberto-bangkok',
          Nome: 'Bangkok',
          TipoConstrucao: 'Térrea',
          Codigo: '114',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_bangkok_914cff52cf.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Bangkok da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 7.15,
          ComprimentoTerreno: 20,
          AreaConstruida: 70.23,
          Quarto: 2,
          Banheiro: 1,
          Garagem: 1,
          MiniDescricao:
            'Projeto de Casa Com 70 m² de área com Conceito Aberto e Área Gourmet',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-casa-com-cozinha-americana-e-2-quartos-quebec',
          Nome: 'Quebec',
          TipoConstrucao: 'Térrea',
          Codigo: '113',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_quebec_62342c4164.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Quebec da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 11,
          ComprimentoTerreno: 30,
          AreaConstruida: 87.22,
          Quarto: 2,
          Banheiro: 2,
          Garagem: 1,
          MiniDescricao:
            'Planta de Casa Com 80m², Cozinha Americana e 2 Dormitórios',
          AreaGourmet: false,
          Piscina: false,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-de-arquitetura-em-aclive-4-suites-chile',
          Nome: 'Chile',
          TipoConstrucao: 'Sobrado',
          Codigo: '112',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_chile_2577e90002.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Chile da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 15,
          ComprimentoTerreno: 40,
          AreaConstruida: 388.55,
          Quarto: 4,
          Banheiro: 6,
          Garagem: 2,
          MiniDescricao: 'Projeto Arquitetônico De Alto Padrão Com 4 Suítes',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-de-casa-pequena-2-dormitorios-madrid',
          Nome: 'Madrid',
          TipoConstrucao: 'Térrea',
          Codigo: '111',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_madrid_df01edfbe4.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Madrid da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 15,
          ComprimentoTerreno: 30,
          AreaConstruida: 107.95,
          Quarto: 2,
          Banheiro: 2,
          Garagem: 2,
          MiniDescricao:
            'Projeto de Casa Pequena Com 2 Quartos, Jardim de Inverno, Cozinha Integrada',
          AreaGourmet: false,
          Piscina: false,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-casa-com-piscina-e-sauna-africa',
          Nome: 'África',
          TipoConstrucao: 'Térrea',
          Codigo: '110',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_africa_49db4a2758.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto África da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 15.2,
          ComprimentoTerreno: 39.8,
          AreaConstruida: 234.6,
          Quarto: 4,
          Banheiro: 4,
          Garagem: 2,
          MiniDescricao:
            'Planta de Casa Com Piscina, Sauna, 4 Suítes e Área Gourmet',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-sobrado-com-fachada-moderna-florida',
          Nome: 'Flórida',
          TipoConstrucao: 'Sobrado',
          Codigo: '109',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_florida_8e9ab765e9.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Flórida da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 10,
          ComprimentoTerreno: 30,
          AreaConstruida: 207.93,
          Quarto: 3,
          Banheiro: 3,
          Garagem: 2,
          MiniDescricao:
            'Projeto de Sobrado Com Fachada Moderna e Ambientes Integrados',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-pronto-terreo-com-conceito-fechado-suica',
          Nome: 'Suíça',
          TipoConstrucao: 'Térrea',
          Codigo: '108',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_suica_b5aaab8397.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Suíça da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 12.5,
          ComprimentoTerreno: 30,
          AreaConstruida: 174.07,
          Quarto: 3,
          Banheiro: 3,
          Garagem: 2,
          MiniDescricao:
            'Projeto de Casa Térrea Com Área Gourmet, Cozinha de Conceito Fechado',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-casa-com-3-quartos-russia',
          Nome: 'Rússia',
          TipoConstrucao: 'Térrea',
          Codigo: '107',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_russia_1751ab404e.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Rússia da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 12.5,
          ComprimentoTerreno: 30,
          AreaConstruida: 183.15,
          Quarto: 3,
          Banheiro: 3,
          Garagem: 2,
          MiniDescricao: 'Planta De Casa Com 3 Quartos e Conceito Aberto',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-com-fachada-moderna-sydney',
          Nome: 'Sydney',
          TipoConstrucao: 'Térrea',
          Codigo: '106',
          midia: {
            thumbnail: {
              url: '/uploads/CAPA_SITE_sydney_5a13c0e9bb.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Sydney da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 15,
          ComprimentoTerreno: 30,
          AreaConstruida: 211.56,
          Quarto: 3,
          Banheiro: 3,
          Garagem: 2,
          MiniDescricao:
            'Planta Pronta Com Fachada Moderna e Ambientes Integrados',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-casa-terrea-com-3-dormitorios-texas',
          Nome: 'Texas',
          TipoConstrucao: 'Térrea',
          Codigo: '105',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_texas_82260f34b6.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Texas da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 13.3,
          ComprimentoTerreno: 30,
          AreaConstruida: 171.02,
          Quarto: 3,
          Banheiro: 3,
          Garagem: 2,
          MiniDescricao:
            'Planta Térrea Com Piscina e Deck Integrados a Área Gourmet',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-com-pe-direito-duplo-europa',
          Nome: 'Europa',
          TipoConstrucao: 'Sobrado',
          Codigo: '104',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_europa_18f7e27cc3.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Europa da Archshop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 15,
          ComprimentoTerreno: 30,
          AreaConstruida: 254.33,
          Quarto: 3,
          Banheiro: 5,
          Garagem: 2,
          MiniDescricao: 'Projeto De Sobrado Moderno Com Pé Direito Duplo ',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: true,
          __typename: 'Projeto',
        },
        {
          slug: 'projeto-terreo-com-3-quartos-canada',
          Nome: 'Canadá',
          TipoConstrucao: 'Térrea',
          Codigo: '103',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_canada_6f3e414e90.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto  Canadá da Archshop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 15,
          ComprimentoTerreno: 40,
          AreaConstruida: 225.78,
          Quarto: 3,
          Banheiro: 3,
          Garagem: 2,
          MiniDescricao:
            'Planta de Casa Térrea com Conceito Aberto, 3 quartos e Área Gourmet',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'planta-de-casa-pequena-monaco',
          Nome: 'Mônaco',
          TipoConstrucao: 'Térrea',
          Codigo: '102',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_monaco_6c38211d8c.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto Mônaco da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 12,
          ComprimentoTerreno: 20,
          AreaConstruida: 96.37,
          Quarto: 2,
          Banheiro: 2,
          Garagem: 2,
          MiniDescricao:
            'Planta de Casa Pequena e Moderna com  Quartos e Uma Suíte',
          AreaGourmet: false,
          Piscina: false,
          Escritorio: false,
          __typename: 'Projeto',
        },
        {
          slug: 'sobrado-com-area-gourmet-new-york',
          Nome: 'New York',
          TipoConstrucao: 'Sobrado',
          Codigo: '101',
          midia: {
            thumbnail: {
              url: '/uploads/projeto_new_york_5505994b06.jpg',
              width: 960,
              height: 540,
              alternativeText: 'Foto do projeto New York da ArchShop',
              __typename: 'UploadFile',
            },
            __typename: 'Midia',
          },
          LarguraTerreno: 15,
          ComprimentoTerreno: 30,
          AreaConstruida: 256.78,
          Quarto: 3,
          Banheiro: 4,
          Garagem: 2,
          MiniDescricao: 'Planta de Casa Sobrado Com Área Gourmet e Piscina',
          AreaGourmet: true,
          Piscina: true,
          Escritorio: false,
          __typename: 'Projeto',
        },
      ],
      icone: {
        TamanhoTerreno: {
          url: '/uploads/tamanho_terreno_943271ce07.svg',
          width: 64,
          height: 64,
          alternativeText: 'Ícone de tamanho de terreno',
          __typename: 'UploadFile',
        },
        AreaConstruida: {
          url: '/uploads/area_construida_f61debd2b7.svg',
          width: 64,
          height: 64,
          alternativeText: 'Ícone de área construída',
          __typename: 'UploadFile',
        },
        Quarto: {
          url: '/uploads/quarto_76b0ab0687.svg',
          width: 64,
          height: 64,
          alternativeText: 'Ícone de quarto',
          __typename: 'UploadFile',
        },
        Banheiro: {
          url: '/uploads/baheiro_ae95e2e5a3.svg',
          width: 64,
          height: 64,
          alternativeText: 'Ícone de banheiro',
          __typename: 'UploadFile',
        },
        Garagem: {
          url: '/uploads/garagem_88a926ebef.svg',
          width: 64,
          height: 64,
          alternativeText: 'Ícone de garagem',
          __typename: 'UploadFile',
        },
        __typename: 'Icones',
      },
      todosProjeto: {
        Seo: {
          Titulo: 'Veja Todos Os Projetos Disponíveis no Nosso Site',
          Descricao:
            'Uma página inteira com todos os projetos prontos da ArchShop para você interagir com o melhor da arquitetura. Veja as vantagens de comprar seu projeto pronto.',
          __typename: 'ComponentOutroSeo',
        },
        __typename: 'TodosProjetos',
        Banner: {
          Imagem: {
            url: '/uploads/banner_todos_projetos_6617335dc6.jpg',
            alternativeText: 'Projeto desenvolvido pela ArchShop',
            __typename: 'UploadFile',
          },
          Titulo: 'Quais as vantagens de adquirir um Projeto Pronto?',
          Descricao:
            'Existem muitas vantagens em comprar um projeto pronto, pode até parecer que a única vantagem no final é o preço, por ser um projeto mais barato, mas na verdade, não é bem assim. As pessoas que nos procuram preferem ter uma planta de casa pré-definida, desta maneira é possível ver o resultado final e como será a sua casa ao fim da obra, tornando o projeto um produto de fácil acesso, você pode visualizar o seu projeto pronto já na largada.',
          __typename: 'ComponentTodosProjetosBanner',
        },
        Filtro: {
          Titulo: 'Confira o nosso catálogo completo!',
          Subtitulo:
            'São diversas opções de plantas prontas para você escolher e dar início ao seu projeto dos sonhos!',
          TamanhoTerreno: [
            { Tamanho: '5x30', __typename: 'ComponentOutroTamanhoTerreno' },
            { Tamanho: '10x25', __typename: 'ComponentOutroTamanhoTerreno' },
            { Tamanho: '12x25', __typename: 'ComponentOutroTamanhoTerreno' },
            { Tamanho: '12x30', __typename: 'ComponentOutroTamanhoTerreno' },
            { Tamanho: '14x30', __typename: 'ComponentOutroTamanhoTerreno' },
            { Tamanho: '15x30', __typename: 'ComponentOutroTamanhoTerreno' },
            { Tamanho: '15x40', __typename: 'ComponentOutroTamanhoTerreno' },
            { Tamanho: '25x40', __typename: 'ComponentOutroTamanhoTerreno' },
            { Tamanho: '30x40', __typename: 'ComponentOutroTamanhoTerreno' },
            { Tamanho: '60x60', __typename: 'ComponentOutroTamanhoTerreno' },
          ],
          Icone: {
            url: '/uploads/casa_light_acfc167401.svg',
            width: 64,
            height: 64,
            alternativeText: 'Ícone de uma casa',
            __typename: 'UploadFile',
          },
          IconeMobile: {
            url: '/uploads/filtro_mobile_54cb145c72.svg',
            width: 32,
            height: 32,
            alternativeText: '',
            __typename: 'UploadFile',
          },
          __typename: 'ComponentTodosProjetosFiltro',
        },
        Metragem: {
          Titulo: 'Metragem do projeto',
          Opcoes: [
            { Texto: '100', __typename: 'ComponentTodosProjetosTexto' },
            { Texto: '200', __typename: 'ComponentTodosProjetosTexto' },
            { Texto: '300', __typename: 'ComponentTodosProjetosTexto' },
            { Texto: '400', __typename: 'ComponentTodosProjetosTexto' },
            { Texto: '500', __typename: 'ComponentTodosProjetosTexto' },
          ],
          __typename: 'ComponentTodosProjetosMetragem',
        },
        Quarto: {
          Titulo: 'Número de quartos',
          Opcao: [
            { Texto: '1', __typename: 'ComponentTodosProjetosTexto' },
            { Texto: '2', __typename: 'ComponentTodosProjetosTexto' },
            { Texto: '3', __typename: 'ComponentTodosProjetosTexto' },
            { Texto: '4', __typename: 'ComponentTodosProjetosTexto' },
            { Texto: '5', __typename: 'ComponentTodosProjetosTexto' },
          ],
          __typename: 'ComponentTodosProjetosQuarto',
        },
        Caracteristicas: {
          Titulo: 'Características',
          Opcao: [
            {
              Texto: 'Área Gourmet',
              __typename: 'ComponentTodosProjetosTexto',
            },
            { Texto: 'Piscina', __typename: 'ComponentTodosProjetosTexto' },
            { Texto: 'Escritório', __typename: 'ComponentTodosProjetosTexto' },
          ],
          __typename: 'ComponentTodosProjetosCaracteristicas',
        },
        Tipo: {
          Titulo: 'Tipo de construção',
          Opcao: [
            { Texto: 'Térrea', __typename: 'ComponentTodosProjetosTexto' },
            { Texto: 'Sobrado', __typename: 'ComponentTodosProjetosTexto' },
          ],
          __typename: 'ComponentTodosProjetosTipo',
        },
        Pesquisa: {
          Placeholder: 'Pesquisar...',
          Icone: {
            url: '/uploads/pesquisa_cd758cb03c.svg',
            width: 64,
            height: 64,
            alternativeText: '',
            __typename: 'UploadFile',
          },
          __typename: 'ComponentTodosProjetosPesquisa',
        },
        Contato: {
          Imagem: {
            url: '/uploads/whatsapp_48a982d6b8.svg',
            width: 64,
            height: 64,
            alternativeText: 'Ícone do Whatsapp',
            __typename: 'UploadFile',
          },
          Link: 'https://api.whatsapp.com/send?phone=5519974121935&amp;text=Olá, estava navegando em seu website e gostaria de informações sobre...',
          __typename: 'ComponentTodosProjetosContato',
        },
      },
      seotitulo: 'Veja Todos Os Projetos Disponíveis no Nosso Site',
      seodescricao:
        'Uma página inteira com todos os projetos prontos da ArchShop para você interagir com o melhor da arquitetura. Veja as vantagens de comprar seu projeto pronto.',
    },
    __N_SSG: true,
  };

  console.log(data);
  //Component render
  return (
    <Row>
      {data.pageProps.projetos.map((projeto) => (
        <Col
          md={4}
          key={projeto.Nome}
          className="d-flex justify-content-center flex-column"
        >
          <img
            src={
              'https://archshop.com.br/_next/image?url=https%3A%2F%2Fdashboard.archshop.com.br' +
              projeto.midia.thumbnail.url +
              '&w=1920&q=75'
            }
            width="100%"
          />
          {projeto.ComprimentoTerreno} x {projeto.LarguraTerreno}
          <br />
          {projeto.AreaConstruida}
          <br />
          {projeto.Quarto}
          <br />
          {projeto.Banheiro}
          <br />
          {projeto.Garagem}
          <br />
          {projeto.slug}
        </Col>
      ))}
    </Row>
  );
}

export default ProjectsList;
